EE_INCS += -I$(PS2SDK)/ee/include -I$(PS2SDK)/common/include -I.
EE_CFLAGS += -std=gnu99 -fgnu89-inline -D_EE -Os -G0 -Wall -Wextra -Werror -ffreestanding -fno-builtin -fno-pic -mno-abicalls -ffunction-sections -fdata-sections $(EE_DEFS)
EE_C_COMPILE = $(EE_CC) $(EE_CFLAGS) $(EE_INCS)

$(EE_LIB): $(EE_OBJS) $(EE_MAKEFILES)
	@mkdir -p $(@D)
	@rm -f $@
	$(EE_AR) rcs $@ $(EE_OBJS)
