EE_GCC_MAJOR := $(firstword $(subst ., ,$(shell $(EE_CC) -dumpversion)))
EE_INLINE_FLAGS = $(if $(filter 2 3,$(EE_GCC_MAJOR)),,-fgnu89-inline)
EE_INCS += -I$(PS2SDK)/ee/include -I$(PS2SDK)/common/include -I.
EE_CFLAGS += -std=gnu99 $(EE_INLINE_FLAGS) -D_EE -Os -G0 -Wall -W $(if $(filter 2 3,$(EE_GCC_MAJOR)),,-Werror) -ffreestanding -fno-builtin -fno-pic -mno-abicalls -ffunction-sections -fdata-sections $(EE_DEFS)
EE_C_COMPILE = $(EE_CC) $(EE_CFLAGS) $(EE_INCS)

$(EE_LIB): $(EE_OBJS) $(EE_MAKEFILES)
	@mkdir -p $(@D)
	@rm -f $@
	$(EE_AR) rcs $@ $(EE_OBJS)
